### ISSUE TITLE
Bluetooth Indicator

### ISSUE THREAD

**Issue by mrpaulblack** [Chrysostomus/limepanel#2]
This is a feature request. Would be nice, if you could write a a Bluetooth indicator for the panel, like the wlan/wired indicator.

**Comment by Chrysostomus** [comment]
What functionality would it have? Would it not be better to enable systemtray in the settings and use some bluetooth applet?

**Comment by MrPaulBlack** [comment]
well I used staleonetray in the past, but it got rendered under lemonbar. Btw I am using Manjaro Bspwm...
